### PR TITLE
Migration of tags app for postgres

### PR DESCRIPTION
**Pull request by mbehrle**
My old production DB is migrating with these changes.

Subject to test: initialsetup of a new DB for sqlite and postgres (hopefully done by travis;)

### CODE REVIEW

**Comment by mbehrle** [comment]
Still one little issue: Reusing the tag_ids in the SQL statements causes a missing update of the serial sequence tags_tag_id_seq (for postgres). Either the SQL should be changed to not reuse the old ids ot the sequence or next_value should be set to count+1 of actual tag ids.

**Comment by mbehrle** [comment]
@rosarior My local tests with data DBs (postgres) and travis now passing. Of course I would appreciate more testing from someone else, with other DBMS. Please have a look at it and merge, if you feel adequate (one day before release). OTOH i have the strong feeling, that migration of tag data will fail anyway with any DBMS with current code. Did someone else do a migration test with a DB containing tag data?

**Comment by rosarior** [comment]
I have not been able to duplicate the conditions for the bug. Using the Vagrant image with postgresql as a DB the syncdb and migrate command run without problem. At what migration of the tags app was you old production DB? I would like to have a repeatable error to check things before and after the patch.

**Comment by mbehrle** [comment]
* Roberto Rosario: " Re: [mayan-edms] Migration of tags app for postgres
  (#159)" (Mon, 09 Feb 2015 11:36:07 -0800):

> I have not been able to duplicate the conditions for the bug. Using the
> Vagrant image with postgresql as a DB the syncdb and migrate command run
> without problem. At what migration of the tags app was you old production DB?
> I would like to have a repeatable error to check things before and after the
> patch.

My production DB currently is running mayan 1.0, thus having no migration at
all for the tags app. The database contains some tags (defined from Simple
permit management setup (Official) of the removed bootstrap app). There are no
documents assigned with any tags.

The creation of an empty database with initialsetup also worked for me, the
error in #154 popped up with this production database with content. So perhaps
it will be sufficient to import just the tags settings from the mentioned
bootstrap setup (joined below).



    {
        "pk": 1, 
        "model": "taggit.tag", 
        "fields": {
            "name": "Permit approved", 
            "slug": "approved"
        }
    }, 
    {
        "pk": 2, 
        "model": "taggit.tag", 
        "fields": {
            "name": "Permit denied", 
            "slug": "permit-denied"
        }
    }, 
    {
        "pk": 3, 
        "model": "taggit.tag", 
        "fields": {
            "name": "For technical review", 
            "slug": "for-technical-review"
        }
    },




    {
        "pk": null, 
        "model": "tags.tagproperties", 
        "fields": {
            "color": "gry", 
            "tag": 1
        }
    }, 
    {
        "pk": null, 
        "model": "tags.tagproperties", 
        "fields": {
            "color": "red", 
            "tag": 2
        }
    }, 
    {
        "pk": null, 
        "model": "tags.tagproperties", 
        "fields": {
            "color": "yel", 
            "tag": 3
        }
    },


-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by rosarior** [comment]
I'm still unable to replicate this and am hesitant to add custom SQL, but you experiencing this issue to me is enough motive to delay the release until this is better understood and properly fixed.

**Comment by mbehrle** [comment]
* Roberto Rosario: " Re: [mayan-edms] Migration of tags app for postgres
  (#159)" (Mon, 09 Feb 2015 23:23:14 -0800):

> I'm still unable to replicate this and am hesitant to add custom SQL, but you
> experiencing this issue to me is enough motive to delay the release until
> this is better understood and properly fixed.

I think, it was worth doing so (not because of me, but because this issue could
have hit others not using postgres). The actual solution is much cleaner and
since South also recommends to use/test against PostgreSQL (for good reasons)
we are well advised to do so (PostgreSQL being my prefered DBMS anyway..;).

Thanks for your patience and looking into it!

-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by mbehrle** [comment]
Thx for your solution preserving the use of the ORM!

**Pull request closed without merging**
